convert function based view in class based view
CITGuru/todoapp pull request #7
Opened 2020-05-08 04:45 UTC by shahzad-chauddhary

2020-05-09 06:21 UTC, shahzad-mycroft requested changes

2020-05-09 06:21 UTC, shahzad-mycroft commented on todolist/views.py
> +    template_name = 'index.html'
Better to inherit from Template View

2020-05-09 06:21 UTC, shahzad-mycroft commented on todolist/views.py
> +# def index(request): #the index
Create a from view and handle the post in it

2020-05-13 09:39 UTC, shahzad-mycroft approved these changes

2020-05-13 10:05 UTC, shahzad-chauddhary commented
task check

2020-05-13 10:05 UTC, closed without merging